### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Silvenga** [tinyclues/saltpad#26]
I'm trying to resolve the dependencies (one traceback at a time). Saltpad appears to want `_winreg`, which to my understanding does not exist for platforms other than Windows (I'm assuming that Saltpad works under Linux). This makes me think that my dependencies are a little messed up. What are the dependencies of Saltpad?

**Comment by Lothiraldan** [comment]
I've just made some cleaning of the repository by removing some legacy code and remove some dependencies.

The dependencies are theses ones now: https://github.com/tinyclues/saltpad/blob/master/requirements.txt

It also should works when doing a python setup.py install.

Sorry for the inconvenience, saltpad should be easy to setup.

**Comment by Silvenga** [comment]
Awsome! I can't believe I missed that.

**Comment by yrdevops** [comment]
I'm getting this issue trying to run on Ubuntu 14.04.1
I've tried going thru the list of dependencies, I've tried running python setup.py install.
Still seeing the same issue:
```
$ python app.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "app.py", line 435, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 622, in run_simple
    reloader_type)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 269, in run_with_reloader
    reloader.run()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 159, in run
    for filename in chain(_iter_module_files(), self.extra_files):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 70, in _iter_module_files
    for package_path in getattr(module, '__path__', ()):
  File "/usr/lib/python2.7/dist-packages/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python2.7/dist-packages/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/dist-packages/six.py", line 76, in _import_module
    __import__(name)
ImportError: No module named _winreg
```

**Comment by yrdevops** [comment]
The answer seems to be here: http://stackoverflow.com/questions/28241989/flask-app-restarting-with-stat

**Comment by Lothiraldan** [comment]
@yrdevops It's likely to be related to this issue in six: https://bitbucket.org/gutworth/six/issue/99/six-and-inspect-importerror-_winreg-module

**Comment by Silvenga** [comment]
@yrdevops installing `wheel` got me past that for some reason. It was the only dep that I was missing.

**Comment by Lothiraldan** [comment]
Thank you for your comment @Silvenga, I will force the werkzeug version in my dependencies.
