### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by schlagify** [tinyclues/saltpad#32]
Hi, I have installed saltpad into a virtualenv and am running it via supervisor.   Before running it with supervisor, I updated the `default_settings.py` file to change HOST to a routable IP (saltpad runs on my salt-master server, so it can't only listen on the loopback IP).  I seem to be able to authenticate when logging in using a web browser (at least it doesn't give me an auth error), however on the next screen I get the below error.  

```
requests.exceptions.ConnectionError
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
Traceback (most recent call last):
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/src/saltpad/saltpad/saltpad/app.py", line 65, in login
    user_token = client.login(form['username'].data, form['password'].data)
  File "/var/src/saltpad/saltpad/saltpad/core.py", line 56, in login
    headers=headers, verify=self.verify_ssl)['return'][0]['token']
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/src/saltpad/saltpad/saltpad/core.py", line 25, in request
    response = super(HTTPSaltStackSession, self).request(*args, **kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

My guess is this could be related to my configuration change?  Maybe it's expecting it to be listening on 127.0.0.1  (though I did update `default_settings.py`)?

My supervisor configuration looks like this:

```
[group:salt]
programs=saltpad

[program:saltpad]
command=/bin/bash -c "cd /var/src/saltpad/saltpad/saltpad; /var/src/saltpad/bin/python /var/src/saltpad/saltpad/saltpad/app.py"
stdout_logfile=/var/log/supervisor/saltpad.log
redirect_stderr=true
autostart=true
autorestart=unexpected
daemon=false
umask=022
```

My supervisor log gives this info:
```
10.10.251.226 - - [02/Mar/2015 18:31:51] "POST /login?next=%2F HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/src/saltpad/saltpad/saltpad/app.py", line 65, in login
    user_token = client.login(form['username'].data, form['password'].data)
  File "/var/src/saltpad/saltpad/saltpad/core.py", line 56, in login
    headers=headers, verify=self.verify_ssl)['return'][0]['token']
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/src/saltpad/saltpad/saltpad/core.py", line 25, in request
    response = super(HTTPSaltStackSession, self).request(*args, **kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

My virtualenv details are below..

```
source /var/src/saltpad/bin/activate
pip freeze
Flask==0.10.1
Flask-WTF==0.11
Jinja2==2.7.3
MarkupSafe==0.23
WTForms==2.0.2
Werkzeug==0.10.1
argparse==1.2.1
distribute==0.6.24
itsdangerous==0.24
pymongo==2.8
requests==2.5.3
wheel==0.22.0
wsgiref==0.1.2
```

**Comment by Lothiraldan** [comment]
Hi, the recommended way to set the HOST is to copy the local_settings.py.sample to local_settings.py and update this file. The file default_settings.py will be update by me if needed in the next release and so your changes may be overwritten.

I just pushed a commit which should make the exception message more useful, I think the URL of your salt-api is misconfigured and saltpad fails to connect to the one configured which is, if you didn't change the API_URL, "localhost:8000". Do you have a salt-api running in local on localhost:8000 ?

**Comment by schlagify** [comment]
Hi, thank you for the tips.  I returned default_settings.py to it's original state, and made a copy of local_settings.py.sample to local_settings.py.  

```
# TODO: If salt-master is not in localhost, uncomment and change API URL
API_URL = 'https://[redacted]:8000/'
# TODO: Generate a random key with os.urandom(24)
SECRET_KEY = ''

# Uncomment next line if you want to add sentry support
# You'll also need to install raven[flask]
# SENTRY_DSN = "https://YOUR_SENTRY_DSN"

# Uncomment next line if your API use a self-signed HTTPS certificate
VERIFY_SSL = False

# You can make saltpad bind 0.0.0.0 (all server address) but you should
# only bind 0.0.0.0 for testing purposes, you should really deploy
# saltpad in production using a wsgi server (like gunicorn or chaussette)
# behind nginx, you have been warned!
HOST = "[redacted]"
```

For the `SECRET_KEY`, do I need to just generate something like an md5 hash and place it in local_settings.py, or do I need to also add the key somehow to salt-api?   Apologies in advance, this is all very new to me.


```
10.32.25.56 - - [03/Mar/2015 12:35:16] "GET / HTTP/1.1" 302 -
10.32.25.56 - - [03/Mar/2015 12:35:16] "GET /login?next=%2F HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/src/saltpad/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/src/saltpad/saltpad/saltpad/app.py", line 62, in login
    form = LoginForm()
  File "/var/src/saltpad/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/var/src/saltpad/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/var/src/saltpad/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
```

**Comment by Lothiraldan** [comment]
The secret_key is only useful for saltpad, it's use by the web framework to avoid some attack vectors on the web, no need to set the secret_key on salt-api. You can either generate a md5 or use the python code just above in the comment "os.urandom(24)", it will generate a strong enough secret for most cases.

**Comment by schlagify** [comment]
thanks for that info!   closing this out
