### ISSUE TITLE
Salt-api ImportError

### ISSUE THREAD

**Issue by perfecto25** [tinyclues/saltpad#36]
Installing saltpad on Centos7 with py 2.7.5, installed salt-api via pip install

(venv) [root@localhost /opt/saltpad/saltpad]# salt-api -d
Traceback (most recent call last):
 File "/opt/saltpad/saltpad/venv/bin/salt-api", line 4, in <module> import saltapi.cli
 File "/opt/saltpad/saltpad/venv/lib/python2.7/site-packages/saltapi/__init__.py", line 8, in <module> import salt.log #pylint: disable=W0611
ImportError: No module named salt.log

 
(venv) [root@localhost /opt/saltpad/saltpad]# which python
/opt/saltpad/saltpad/venv/bin/python

(venv) [root@localhost /opt/saltpad/saltpad]# python -V
Python 2.7.5

tried installing salt-api again,

(venv) [root@localhost /opt/saltpad/saltpad]# pip install salt-api
Requirement already satisfied (use --upgrade to upgrade): salt-api in ./venv/lib/python2.7/site-packages

**Comment by Lothiraldan** [comment]
Hello @perfecto25, which salt-master version do you use?

```
import salt
salt.__version__
```

**Comment by perfecto25** [comment]
salt-run --version
salt-run 2014.7.1 (Helium)

sorry, im not very good w python, otherwise id troubelshoot it myself.

**Comment by whiteinge** [comment]
This looks like an old error from very old versions of Salt. Did you upgrade to 2014.7 from a previous version? What version of salt-api did pip pull in? (`salt-api --version`)

It might be worth trying to uninstall/reinstall or to nuke all the `.pyc` files from the previous install.

**Comment by Lothiraldan** [comment]
@perfecto25 I think salt-api is installed inside the virtualenv while salt is installed on the system (maybe via system package, right?).

salt-api must be installed next to salt and so should be installed with "sudo pip install salt-api"

Maybe your system package manager already have a package for salt-api, I'm not aware of salt packaging on Centos

**Comment by hsitaa** [comment]
And here it goes same error : 
salt-api -d
Traceback (most recent call last):
  File "/root/saltpad/venv/bin/salt-api", line 4, in <module>
    import saltapi.cli
  File "/root/saltpad/venv/lib/python2.6/site-packages/saltapi/__init__.py", line 8, in <module>
    import salt.log  # pylint: disable=W0611
ImportError: No module named salt.log

salt-run --version
salt-run 2015.5.0 (Lithium)

 python -V
Python 2.6.6

salt-api --version  => throws same error as stated for salt-api -d



info as above requested

**Comment by Lothiraldan** [comment]
@hsitaa Could you run salt-api --version, I think you might use the old salt-api version, the one that are not packaged into salt itself

**Comment by whiteinge** [comment]
That is definitely from the old, standalone version of salt-api. The `import saltapi.cli` path in that traceback no longer exists.

@hsitaa uninstall `salt-api`. Looks like you're installing via Pip; salt-api now ships with Salt so you only need to install `salt` inside your venv and the `salt-api` script should be installed along with that.

**Comment by Lothiraldan** [comment]
@perfecto25 Did you fixed the problem by updating salt-api?
