### ISSUE TITLE
SaltPad timeout when logging in

### ISSUE THREAD

**Issue by KrustyHack** [tinyclues/saltpad#42]
Hi,

I got an error when I log in into saltpad:

```
----------------------------------------
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET / HTTP/1.0" 302 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /login?next=%2F HTTP/1.0" 200 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/css/bootstrap.css HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/font-awesome/css/font-awesome.min.css HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/css/sb-admin.css HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/css/saltpad.css HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/css/dataTables.bootstrap.css HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/css/jsontree.css HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/js/jquery-1.10.2.js HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/js/bootstrap.js HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/js/jsontree.js HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/js/jquery.dataTables.min.js HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/js/dataTables.bootstrap.js HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:41:58] "GET /static/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0 HTTP/1.0" 304 -
172.17.0.2 - - [13/Mar/2015 17:42:02] "POST /login?next=%2F HTTP/1.0" 302 -
172.17.0.2 - - [13/Mar/2015 17:43:31] "GET / HTTP/1.0" 200 -
----------------------------------------
Exception happened during processing of request from ('172.17.0.2', 35587)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

I start saltpad, I go on the login page, no problems, but when I want to log in it loads during 1 minute or more and then go on a timeout.

I figured out that it's because one of my minion doesn't return (host down). is it possible to configure SaltPad to bypass an host if it's down and log in anyway ?

Regards,

**Comment by Lothiraldan** [comment]
Currently, saltpad do several API calls on the main page. If you have a minion down, salt will wait the timeout configured before returning the results. Did you set the timeout value to a non-default value?

On the main page, saltpad also get the latests jobs, do you have a big number of jobs? How do you store them, locally in /var/cache/salt/master/jobs (the default) or do you use a custom job_cache / returner?

**Comment by KrustyHack** [comment]
Hi,

Here is my timeout option in master config file:

```
# Set the default timeout for the salt command and api, the default is 5
# seconds
timeout: 60
```

For the number of jobs, it's quite reasonable. I use Halite to and there is no problem. But I saw the first problem was a non responding minion. I fixed it and now SaltPad work but very slowly at login.

**Comment by Diaoul** [comment]
See #41, it's a general issue. I think saltpad should use some background tasks and somehow report the result back in the browser in a more non-blocking way.

**Comment by bbinet** [comment]
I'm also regularly facing the same issue because several minions are down.
Any news on the state of this issue, and on the background tasks #41 redesign effort since it seems to be the main blocking issue for a better saltpad experience.

**Comment by Lothiraldan** [comment]
@bbinet I start working in a new saltpad version in JS which will allow me to use the websocket endpoint and make a much more responsive interface. In fact, latest Salt PRs have been merged yesterday for full-support of CORS in salt-api.

**Comment by bbinet** [comment]
That is great news @Lothiraldan!
Is there a repository somewhere that we can watch?
So finally websockets are more suitable than the SSE interface (see https://github.com/tinyclues/saltpad/issues/41#issuecomment-85601742)?

**Comment by Lothiraldan** [comment]
Not yet, I was working on making salt-api working with CORS, about the SSE interface, I don't think salt_tornado supports it and as it will be the new default salt-api implementation, I choose websocket but it should be easy to switch either on websocket or on SSE.

**Comment by bbinet** [comment]
Ok, thanks for this information.
If this is helpful, I will be happy to test the new saltpad when an alpha version will be available.

**Comment by Lothiraldan** [comment]
I will try to communicate either as a line in the readme, a message on salt-users or maybe start a dedicated project website
