### ISSUE TITLE
All jobs results are empty

### ISSUE THREAD

**Issue by lrhazi** [tinyclues/saltpad#49]
Hello,

I am running the Dockerfile version included in the repo.

When I execute a job, the returned page is empty. No minions in the list and no actual result content.

I check the actual job output with "salt-run jobs.lookup_jid " and it did match a minion and has command output.

Same behavior when I pick any of the jobs listed in Jobs History, and click to view its output.

My salt master is: salt 2015.2.0rc1-5213-g6fcdeb4 (Lithium)

**Comment by Lothiraldan** [comment]
The salt-master is on localhost, right? You launch a job via saltpad or the salt command-line? Which salt-api implementation do you use? If you can paste your salt-master configuration it would helps a lot to debug the issue (minus any sensible value).

**Comment by lrhazi** [comment]
I debugged further and found that saltpad is getting this, when it sends its call to the salt-api:

```
{u'info': [u'Exception occurred in runner jobs.list_job: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 332, in low
    data[\'return\'] = self.functions[fun](*args, **kwargs)
TypeError: list_job() takes at least 1 argument (0 given)
'], u'return': [u'Exception occurred in runner jobs.lookup_jid: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 332, in low
    data[\'return\'] = self.functions[fun](*args, **kwargs)
TypeError: lookup_jid() takes at least 1 argument (0 given)
']}
```

the above is the result of this :+1: 
```
def job(self, jid, minion=None):
        token = self.get_token()
        headers = {'accept': 'application/json', 'X-Auth-Token': token}
        r = self.session.get(self.urljoin('jobs', jid), headers=headers, verify=self.verify_ssl)
```

I can see in my debugger that jid is set correctly to the job_id...

My salt-master has this added to its config:
```
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  debug: true
```

**Comment by lrhazi** [comment]
Oh, this is when I use saltpad to submit a new job...
but I think the behavior is the same when use saltpad to view the output of any historic job.

**Comment by Lothiraldan** [comment]
This is weird, I checked the rest_cherrypy code for your version and everything seems fine (https://github.com/saltstack/salt/blob/v2015.2.0rc1/salt/netapi/rest_cherrypy/app.py#L938-L1044). Could you try with a stable version?

**Comment by lrhazi** [comment]
I'll see what I can do.. this master is actually my production salt master :)

**Comment by Lothiraldan** [comment]
I will try to test it with rc1 to see if it's works or not

**Comment by lrhazi** [comment]
I switched to rest_tornado, and seems I found a different issue... saltpad looks for a dict key of info, which does not exist:

```
return {'info': r['info'][0], 'return': r['return'][0]}
```

```
$ curl -s http://localhost:8000/jobs/20150424161506333989 -H "Accept: application/json" -H 'X-Auth-Token: f9da72a0e571cb59b90e912807ddd88e'  | python -m json.tool                                                  1 ↵
{
    "return": [
        {
            "Arguments": [
                "uptime"
            ],
            "Function": "cmd.run",
            "Minions": [
                "fradius-p-1.uis.georgetown.edu",
                "fradius-p-2.uis.georgetown.edu"
            ],
            "Result": {
                "fradius-p-1.uis.georgetown.edu": {
                    "return": " 16:15:06 up 31 days, 19 min,  0 users,  load average: 0.00, 0.00, 0.00"
                },
                "fradius-p-2.uis.georgetown.edu": {
                    "return": " 16:15:06 up 31 days, 19 min,  1 user,  load average: 0.00, 0.00, 0.00"
                }
            },
            "StartTime": "2015, Apr 24 16:15:06.333989",
            "Target": "frad*",
            "Target-type": "glob",
            "User": "ml623",
            "jid": "20150424161506333989"
        }
    ]
}
```

**Comment by whiteinge** [comment]
The `lookup_jid` traceback in OP sounds like a bug in Salt-core.
Please try to reproduce on the latest 2015.2 and file an issue on the
main Salt repo if so. Are you using `ext_job_cache` or
`master_job_cache` ?

**Comment by lrhazi** [comment]
Does the latest version of saltpad work with the latest git develop of version of salt ? 
It looks like the latest salt is very different from what saltpad is expecting.. right?

**Comment by whiteinge** [comment]
If different salt versions are producing different output for the same
command that is a regression and should be fixed. Please file an issue on
the main salt repo with the function you are calling and the outputs.

**Comment by Lothiraldan** [comment]
I think it's the same problem as https://github.com/tinyclues/saltpad/issues/40#issuecomment-94496216
