### ISSUE TITLE
for minion in minions_status['up']: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by jagguli** [tinyclues/saltpad#52]
Traceback (most recent call last):
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steven/iress/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/steven/iress/saltpad/saltpad/app.py", line 58, in wrapper
    return view(*args, **kwargs)
  File "/home/steven/iress/saltpad/saltpad/app.py", line 113, in minions_status
    for minion in minions_status['up']:
TypeError: string indices must be integers

**Comment by Lothiraldan** [comment]
Hello @jagguli,

This error may occur when the salt-api doesn't returns the expected output which is weird. Could you give us the versions of your salt-master, the version of your salt-api and which implementation of salt-api do you use (rest-cherrypy or rest-tornado)?

**Comment by jagguli** [comment]
salt-master 2014.7.4 (Helium)
salt-api 2014.7.4

rest_cherrypy

**Comment by Lothiraldan** [comment]
Hi @jagguli, sorry for the delay, I made the choice recently to support only 2015.5.X versions. Could you give it a try with an updated version of salt?
