### ISSUE TITLE
KeyError: 'jid'

### ISSUE THREAD

**Issue by 0312birdzhang** [tinyclues/saltpad#60]
My python version is 2.7.6
When use "Launch a check now" ,show :

```
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/zhangdebo/git/saltpad/saltpad/app.py", line 57, in wrapper
Display the sourcecode for this frameOpen an interactive python shell in this framereturn view(*args, **kwargs)
File "/home/zhangdebo/git/saltpad/saltpad/app.py", line 175, in job_result
job = parse_highstate(job)
File "/home/zhangdebo/git/saltpad/saltpad/utils.py", line 140, in parse_highstate
level = max(level, statuses[step['result']])
KeyError: 'result'
```

When do jobs :

```
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/zhangdebo/git/saltpad/saltpad/app.py", line 57, in wrapper
return view(*args, **kwargs)
File "/home/zhangdebo/git/saltpad/saltpad/app.py", line 307, in redo_job
args=job['info']['Arguments'])['jid']
KeyError: 'jid'

```

**Comment by Routhinator** [comment]
I managed to resolve the 500 error with the missing result key, but I've now hit the jid. Looking into this now.

**Comment by Routhinator** [comment]
This appears to occur whenever a job cannot be deserialized like so:

    [root@saltmaster saltpad]# salt-run jobs.list_jobs
    [CRITICAL] Could not deserialize msgpack message: ��fun_args��jid�20150616205143611166�return�9�biosversion�>rel-1.7.5.1-0-g8936dbb-20141113_115728-nilsson.home.kraxel.org�kernel�Linux�domain�example.com�zmqversion�3.2.5�kernelrelease�3.10.0-123.20.1.el7.x86_64�selinux��enforced�Disabled�enabled¬serialnumber�Not Specified�ip_interfaces��lo��127.0.0.1�::1�eth0��192.168.51.6�fe80::201:a4ff:fea1:ca06�pythonexecutable�/usr/bin/python�fqdn_ip6��mem_total�0�saltversioninfo����SSDs��mdadm��id�git.example.com�osrelease�7.0.1406�ps�ps -efH�systemd��version�208�features�L+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ�fqdn�git.example.com�ip6_interfaces��lo��::1�eth0��fe80::201:a4ff:fea1:ca06�num_cpus�hwaddr_interfaces��lo�00:00:00:00:00:00�eth0�00:01:a4:a1:ca:06�ip4_interfaces��lo��127.0.0.1�eth0��192.168.51.6�osfullname�CentOS Linux�master�salt�ipv4��127.0.0.1�192.168.51.6�ipv6��::1�fe80::201:a4ff:fea1:ca06�cpu_flags� �fpu�de�pse�tsc�msr�pae�mce�cx8�apic�sep�mtrr�pge�mca�cmov�pat�pse36�clflush�mmx�fxsr�sse�sse2�ht�syscall�nx�lm�constant_tsc�nopl�pni�cx16�x2apic�hypervisor�lahf_lm�localhost�git.example.com�lsb_distrib_id�CentOS Linux�fqdn_ip4��192.168.51.6�shell�/bin/sh�nodename�git.example.com�saltversion�2015.5.0�pythonpath��/usr/bin�/usr/lib64/python27.zip�/usr/lib64/python2.7� /usr/lib64/python2.7/plat-linux2�/usr/lib64/python2.7/lib-tk�/usr/lib64/python2.7/lib-old� /usr/lib64/python2.7/lib-dynload�"/usr/lib64/python2.7/site-packages� /usr/lib/python2.7/site-packages�server_id�j���saltpath�%/usr/lib/python2.7/site-packages/salt�osmajorrelease�7�os_family�RedHat�oscodename�Core�osfinger�CentOS Linux-7�pythonversion��final�manufacturer�QEMU�num_gpus�virtual�kvm�cpu_model�Common KVM processor�host�git�biosreleasedate�04/01/2014�productname�!Standard PC (i440FX + PIIX, 1996)�osarch�x86_64�cpuarch�x86_64�osrelease_info��~�locale_info��detectedencoding�UTF-8�defaultlanguage�en_US�defaultencoding�UTF-8�gpus���model�GD 5446�vendor�unknown�path�1/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin�machine_id� a002c740cbbc48008c93335b299e770b�os�CentOS�retcode�successãcmd�_return�_stamp�2015-06-17T00:51:43.714151�fun�grains.items�id�git.example.comd�db.example.comThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
    Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 317, in low
        data['return'] = self.functions[fun](*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/runners/jobs.py", line 211, in list_jobs
        ret = mminion.returners['{0}.get_jids'.format(returner)]()
      File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 282, in get_jids
        for jid, job, _, _ in _walk_through(_job_dir()):
      File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 67, in _walk_through
        job = serial.load(salt.utils.fopen(load_path, 'rb'))
      File "/usr/lib/python2.7/site-packages/salt/payload.py", line 114, in load
        return self.loads(data)
      File "/usr/lib/python2.7/site-packages/salt/payload.py", line 98, in loads
        return msgpack.loads(msg, use_list=True)
      File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
    ExtraData: unpack(b) received extra data.

**Comment by Routhinator** [comment]
Deleting the job resolves it but this seems to be a common thing on my setup at least with the current version of salt. I might be resolved, but it should be error handled.

**Comment by Lothiraldan** [comment]
@0312birdzhang If you already use the 2015.5 version of salt, be sure to have **ALL** your minions using 2015.5 version of salt too.

**Comment by 0312birdzhang** [comment]
@Lothiraldan not all minions using 2015.5. Is this caused the problem?

**Comment by Lothiraldan** [comment]
I think that 2014.X and 2015.X minions returns different format to the master then leading to these kind of errors.

**Comment by Lothiraldan** [comment]
@0312birdzhang @Routhinator Did you had time to update all your minions to 2015.5.X?
