### ISSUE TITLE
Highstate page broken (patch included)

### ISSUE THREAD

**Issue by simonbp** [tinyclues/saltpad#62]
I'm trying out Saltpad for the first time. Thanks for your hard work. It looks great.

When trying to view a highstate, I get an error in my browser and the following in saltpad.log:

```
Exception on /job_result/20150611173726371406 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/saltpad/saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "/var/www/saltpad/saltpad/app.py", line 182, in job_result
    job = parse_highstate(job)
  File "/var/www/saltpad/saltpad/utils.py", line 141, in parse_highstate
    level = max(level, statuses[step['result']])
KeyError: 'result'
```

I'm running the latest master (a366b94e27b9d215619024269901a59024b40789) with salt 2015.5.0.

Fixing the problem involves patching two files:

```
From 5a01843f36943212e9e1bc5de2a4cca6bb6d6d47 Mon Sep 17 00:00:00 2001
From: Brian Simons <bsimons@propertysolutions.com>
Date: Thu, 11 Jun 2015 22:55:51 +0000
Subject: [PATCH] Fix broken highstate parsing

---
 saltpad/templates/macros.jinja | 2 +-
 saltpad/utils.py               | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/saltpad/templates/macros.jinja b/saltpad/templates/macros.jinja
index 2302644..70cd3ce 100644
--- a/saltpad/templates/macros.jinja
+++ b/saltpad/templates/macros.jinja
@@ -4,7 +4,7 @@
 
 {% macro format_value(value) %}
   {% if value is defined and not None %}
-    {% if '\n' in value %}
+    {% if '\n' in value|string %}
       <pre>{{ value }}</pre>
     {% else %}
       {{ value }}
diff --git a/saltpad/utils.py b/saltpad/utils.py
index 715abf5..058c865 100644
--- a/saltpad/utils.py
+++ b/saltpad/utils.py
@@ -113,7 +113,7 @@ def parse_highstate(job):
 
     if job.get('status') != 'running':
 
-        for minion_name, minion_return in job['return'].items():
+        for minion_name, minion_return in job['return']['data'].items():
 
             # Error detected
             if isinstance(minion_return, list):
-- 
1.9.1
```

Is this an actual bug, or am I just doing something weird?

**Comment by Lothiraldan** [comment]
My biggest problem right now is the non-standard response from the API depending on where jobs are stored. It's likely to be the problem with the second patch part.

For the first one, I think it's maybe related to the commit I made improving compatibility with python 2.6 and python 3.

I've two questions:
* Which python version do you use?
* Which job storage do you use? (Default one?)

**Comment by simonbp** [comment]
Thanks for looking into this.

```
# python --version
Python 2.7.6
```

I'm using the default job storage.

```
# salt 'salt' config.get ext_job_cache
salt:
# salt 'salt' config.get job_cache
salt:
# salt 'salt' config.get master_job_cache
salt:
```

**Comment by Routhinator** [comment]
Oops, this is the same issue as #62

**Comment by Lothiraldan** [comment]
The PR is merged now, could you please comment in https://github.com/tinyclues/saltpad/pull/71 if you prefer to see compatibility with 2015.5.X version or 2014.7.X version

**Comment by Lothiraldan** [comment]
@simonbp Is the latest version of saltpad works for you?
