### ISSUE TITLE
500 Error only on "GET /job_result/*"

### ISSUE THREAD

**Issue by Routhinator** [tinyclues/saltpad#64]
I just setup Saltpad and I can see my Minions status and accept/reject their keys. Setup seems ok except when I attempt to do anything that hits the /job_result/ URL. (Deploy now, Launch a check now, etc)

Example:

    "GET /job_result/2015061416333742453423?minion=serv.example.com&renderer=highstate HTTP/1.0" 500

Result is allways error 500. I've tailed my NGINX error log, and nothing is logged when it happens.

Salt master log is similarly uneventful:

    2015-06-14 16:27:19,158 [py.warnings      ][WARNING ][6772] /usr/lib/python2.7/site-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"
    2015-06-14 16:27:20,355 [py.warnings      ][WARNING ][6835] /usr/lib/python2.7/site-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"
    2015-06-14 16:27:20,592 [py.warnings      ][WARNING ][6863] /usr/lib/python2.7/site-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"

(Those lines are output three times on each Error 500)

Cannot find anything else of use in /var/log/messages. I even went crazy and did tail -f /var/log* and tail -f /var/log/*/* to see if anything was being put in any log anywhere... nothing. Really lost on where to look.

**Comment by Routhinator** [comment]
Ok, now that I've run some jobs (this is a fresh salt-master setup) I'm getting Error 500 on all URLs. Still no evidence of why in the logs. I've set my Secret as per the install docs... not sure what's up here.

**Comment by Routhinator** [comment]
Aha.. an error:

    Could not deserialize msgpack message: ��fun_args��jid�20150614184746697203�returnçretcode�successãcmd�_return�_stamp�2015-06-14T22:47:46.859970�fun�test.ping�id�server.example.comoThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.

This only happens with SaltPad however. SaltStack itself is unaffected.

**Comment by Routhinator** [comment]
Just tried deleting the jobs in the jobs cache in case that was it... no go.

Also I can still hit any URL that does not attempt to ping the hosts.

For example:

    /minions_keys

**Comment by Routhinator** [comment]
Generating a new secret key also seems ineffective.

**Comment by Routhinator** [comment]
Turns out this error was from the 'salt-run jobs.list_jobs' command.

When I ran a job from the SaltPad interface it caused the job to get stuck on the server.example.com host and prevented any further job listings from that host. Work around was to log on to the minion and clear the job cache, then restart the minion.

**Comment by Routhinator** [comment]
Spoke too soon. Original issue still exists. Turns out the error and it's fix was coincidental.
 
    /job_result/20150614233930829425?minion=server.example.com&renderer=highstate

This is the url hit after selecting 'Launch a check now' - it returns error 500.

**Comment by Lothiraldan** [comment]
Hi @Routhinator, which version of Saltstack do you use on your master + your minions? Do you use any job cache?

**Comment by Routhinator** [comment]
Master:

    Salt: 2015.5.0

Minions:

    salt-minion 2015.5.0 (Lithium)

I haven't setup any job caches outside of what is setup by default with the salt-master/salt-minion packages on CentOS

**Comment by Routhinator** [comment]
There's a real error, found out where my saltpad output was going. True error on job result only. Call was a state.highstate. 

    Exception on /job_result/20150615233604879753 [GET]
    Traceback (most recent call last):
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "./saltpad/app.py", line 63, in wrapper
        return view(*args, **kwargs)
      File "./saltpad/app.py", line 182, in job_result
        job = parse_highstate(job)
      File "./saltpad/utils.py", line 137, in parse_highstate
        level = max(level, statuses[step['result']])
    KeyError: 'result'

**Comment by Routhinator** [comment]
Pull #66 fixes this.

Also a grammar error on the dashboard is fix as well.

**Comment by Routhinator** [comment]
Oops, this is the same issue as #62

**Comment by Routhinator** [comment]
Looks like we're not out of the woods yet, however big improvement. The Job page for a state.highstate continues to run, however there was no return by the look of it. Seems like 'changes' isn't being checked for a value.

    Exception on /job_result/20150616061105758230 [GET]
    Traceback (most recent call last):
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "./saltpad/app.py", line 63, in wrapper
        return view(*args, **kwargs)
      File "./saltpad/app.py", line 182, in job_result
        job = parse_highstate(job)
      File "./saltpad/utils.py", line 137, in parse_highstate
        if not step['changes']:
    KeyError: 'changes'

**Comment by Routhinator** [comment]
Correction, that is your check.. hmmm. Looking into it.

**Comment by Routhinator** [comment]
Found it, submitting a new pull in a moment.

**Comment by Routhinator** [comment]
Pull #67 will correct the Error 500 when the changes key is not returned.

**Comment by Lothiraldan** [comment]
Thank you for the PR, don't remember why I filter out changes, maybe I should change the output to accept empty changes

**Comment by Routhinator** [comment]
Ok, I have the changes check working... on to the next line:

    Exception on /job_result/20150616064414382551 [GET]
    Traceback (most recent call last):
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "./saltpad/app.py", line 63, in wrapper
        return view(*args, **kwargs)
      File "./saltpad/app.py", line 182, in job_result
        job = parse_highstate(job)
      File "./saltpad/utils.py", line 143, in parse_highstate
        if step['result'] is False and "One or more requisite failed" in step['comment']:
    KeyError: 'result'

**Comment by Routhinator** [comment]
Pull #68 fixes the changes key issues. But now it's tripping up on line 143 of utils.py

I have to head to work but I'll look at that line tonight to see it can be dealt with unless you beat me to it . :)

**Comment by Routhinator** [comment]
Off the top of my head changing 

    if step['result'] is False and "One or more requisite failed" in step['comment']:

To:

    if not step.get('result') and "One or more requisite failed" in step['comment']:

should cover it.

**Comment by Lothiraldan** [comment]
@Routhinator Thank you for your contributions, I will look at them

**Comment by Routhinator** [comment]
So just tried my thought and it worked for changes.. but now comment is empty. Working through it before I update the pull. I'm going to resolve these 500 errors.

**Comment by Routhinator** [comment]
Cumulative commits in PR #68 now resolve this issue with all missing values in a state.highstate call with utils.parse_highstate

**Comment by Lothiraldan** [comment]
The PR is merged now, could you please comment in if you prefer to see compatibility with 2015.5.X version or 2014.7.X version

**Comment by Routhinator** [comment]
Pulled in all the new commits, and I can finally run a sync status. Closing this issue as resolved.
