### ISSUE TITLE
Saltpad error after running it for sometime

### ISSUE THREAD

**Issue by chamambom** [tinyclues/saltpad#78]
Traceback (most recent call last):
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/saltpad/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/saltpad/saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "/opt/saltpad/saltpad/app.py", line 112, in index
    jobs = sorted(list(client.jobs().items()), reverse=True)[:10]
AttributeError: 'unicode' object has no attribute 'items'

**Comment by Lothiraldan** [comment]
WHat version of salt-master and salt-api are you running?

**Comment by chamambom** [comment]
[root@lockdown ~]# rpm -qa | grep salt-master
salt-master-2015.5.2-3.el7.noarch
[root@lockdown ~]# rpm -qa | grep salt-api
salt-api-2015.5.2-3.el7.noarch
[root@lockdown ~]#

**Comment by Lothiraldan** [comment]
Do you have minions in old version? Like 2014.7.X?
