### ISSUE TITLE
ZeroDivisionError on job_result_aggregate.html line 18

### ISSUE THREAD

**Issue by dannydufau** [tinyclues/saltpad#79]
I get an error requesting and aggregate job result on some jobs

`
Traceback (most recent call last):
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/saltpad/saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "/home/ubuntu/saltpad/saltpad/app.py", line 203, in job_result
    renderer=renderer)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/ENV/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/saltpad/saltpad/templates/job_result_aggregate.html", line 1, in top-level template code
    {% extends "job_result.html" %}
  File "/home/ubuntu/saltpad/saltpad/templates/job_result.html", line 2, in top-level template code
    {% extends "base_logged.html" %}
  File "/home/ubuntu/saltpad/saltpad/templates/base_logged.html", line 2, in top-level template code
    {% from "macros.jinja" import print_flash_messages %}
  File "/home/ubuntu/saltpad/saltpad/templates/base.html", line 26, in top-level template code
    {% block body %}
  File "/home/ubuntu/saltpad/saltpad/templates/base_logged.html", line 123, in block "body"
    {% block page %}
  File "/home/ubuntu/saltpad/saltpad/templates/job_result.html", line 47, in block "page"
    {% block job_result %}
  File "/home/ubuntu/saltpad/saltpad/templates/job_result_aggregate.html", line 18, in block "job_result"
    <h3>{{hiding_control('hide_control_minion', True)|safe }} {{ minions|length }} ({{ '{:.0%}'.format(minions|length / total_minions_length) }}) minion(s) with this result:</h3>
ZeroDivisionError: division by zero
`

**Comment by Lothiraldan** [comment]
Did your job targets at least one minion?

**Comment by dannydufau** [comment]
Well, not exactly.  How important is that a minion actually exist to see a job result without an exception?   It occurs whenever runner.jobs executes something like list_job, where the minion is actually the master.  The master can be a minion for this to occur.

my quick fix:
<h3>{{hiding_control('hide_control_minion', True)|safe }} {{ minions|length }} minion(s) with this result:</h3>

**Comment by Lothiraldan** [comment]
Good point, jobs launched by runner were added in latest major version of salt and I didn't check its support. The aggregate renderer was designed for minions first so it's likely to not works very well with runner jobs. Did the normal renderer works for you?

**Comment by dannydufau** [comment]
The normal renderer does not throw an exception, however, there is no content.
