### ISSUE TITLE
Error while running "launch a check now" in saltpad

### ISSUE THREAD

**Issue by SHU17** [tinyclues/saltpad#80]
Hi All,

I am beginner trying to setup saltpad. I get "internal server error" when I try to click on "Launch a Check Now" under minion status.  Here is the stacktrace.  Can you please help?

Exception on /job_result/20150722230824736020 [GET]
Traceback (most recent call last):
  File "saltpad/venv/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "saltpad/venv/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "saltpad/venv/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "saltpad/venv/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "saltpad/venv/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "./saltpad/app.py", line 200, in job_result
    renderer=renderer)
  File "saltpad/venv/lib/python2.6/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "saltpad/venv/lib/python2.6/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "saltpad/venv/lib/python2.6/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "saltpad/venv/lib/python2.6/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "saltpad/./saltpad/templates/job_result_highstate.html", line 2, in top-level template code
    {% extends "job_result.html" %}
  File "saltpad/./saltpad/templates/job_result.html", line 2, in top-level template code
    {% extends "base_logged.html" %}
  File "saltpad/./saltpad/templates/base_logged.html", line 2, in top-level template code
    {% from "macros.jinja" import print_flash_messages %}
  File "saltpad/./saltpad/templates/base.html", line 26, in top-level template code
    {% block body %}
  File "saltpad/./saltpad/templates/base_logged.html", line 123, in block "body"
    {% block page %}
  File "saltpad/./saltpad/templates/job_result.html", line 9, in block "page"
    <h1>{{ job.info.Function }} on {{ job.info.Target }} started at {{ job.info.StartTime }} by {{ job.info.User }} <small>Arguments {{ job.info.Arguments|format_arguments }}  <a href="{{ url_for('redo_job', jid=job.info.jid, minion=minion, renderer=renderer) }}"><button class="btn btn-primary btn-sm"><i class="fa fa-refresh"></i> Redo job with same parameters</button></a></small> </h1>
  File "./saltpad/app.py", line 442, in format_argument
    return " ".join(format_arguments(arguments))
  File "./saltpad/utils.py", line 193, in format_arguments
    yield "--{}={}".format(*list(argument.items())[0])
ValueError: zero length field name in format

**Comment by SHU17** [comment]
upgraded to python 3.3 and it works.

**Comment by Lothiraldan** [comment]
I'm sorry, I didn't have time to look at the issue but which python version do you used before?

**Comment by SHU17** [comment]
Thanks for replying. I used python 2.6.6 before.
