### ISSUE TITLE
Saltpad exception

### ISSUE THREAD

**Issue by SHU17** [tinyclues/saltpad#91]
Hi

When I click on any links after login to saltpad, I see following exception. all minions and master are 2015.5.5 version. Please help. I tried with python 2.6 and got same exception. 

Exception on /minions [GET]
Traceback (most recent call last):
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./saltpad/app.py", line 63, in wrapper
    return view(*args, **kwargs)
  File "./saltpad/app.py", line 132, in minions_status
    return render_template('minions.html', minions=minions, jobs=jobs)
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/jinja2/environment.py", line 899, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/jinja2/environment.py", line 675, in handle_exception
    raise exc_value.with_traceback(tb)
  File "./saltpad/templates/minions.html", line 1, in <module>
    {% extends "base_logged.html" %}
  File "./saltpad/templates/base_logged.html", line 2, in <module>
    {% from "macros.jinja" import print_flash_messages %}
  File "./saltpad/templates/base.html", line 26, in <module>
    {% block body %}
  File "./saltpad/templates/base_logged.html", line 123, in <module>
    {% block page %}
  File "./saltpad/templates/minions.html", line 37, in <module>
    {% for role in minion_data.roles %}<li>{{ role }}</li>{% endfor %}
TypeError: 'NoneType' object is not iterable

**Comment by SHU17** [comment]
I did some debugging and if I replace following section from minions.html (under templates)
{% for role in  minion_data.roles %}
   <li>{{ role }}</li>
{% endfor %}

with

{{ minion_data.roles }}

This works but formatting doesnt work. It shows roles like ['oracle', 'MQ', 'mysql'].

**Comment by Lothiraldan** [comment]
It's very weird, could you give me the output of this command:

```
salt 'YOUR_MINION' grains.get roles
```

And the portion of the minion config defining the roles of the minion please.

Sorry for the lag, I want to fix this problem with you.

**Comment by SHU17** [comment]
Sorry, I was out for couple of days so did not see your reply.  Thanks for your help.  Here is the minion output:

[root@saltmaster01 salt]# salt 'testhost1' grains.get roles
testhost1:
    - db:oracle
    - db:mysql
    - app:MQ

Here is the Minion Config:

grains:
  roles:
     - db:oracle
     - db:mysql
     - app:MQ

**Comment by SHU17** [comment]
Hi

did you have a chance to take a look at this?

**Comment by Lothiraldan** [comment]
I don't managed to find how the minion roles could ever be set to None, do you have for one or your minion this kind of line of config:

```
roles:
```

or

```
roles: Null
```

?

Anyway, I pushed a possible fix for this problem, could you try the PR https://github.com/tinyclues/saltpad/pull/92 by pulling the 91-fix branch and try again?

**Comment by SHU17** [comment]
Sorry for the delay. The fix works really well. Thanks again.

**Comment by Lothiraldan** [comment]
Thank you for the report.
